### ISSUE TITLE
Unclear reason behind `Eth::Abi::DecodingError` after calling RPC function

### ISSUE THREAD

**Issue by alex-damian-negru** [q9f/eth.rb#104]
## Description

While trying to call the `balanceOf` RPC method on the [CRYPTOPUNKS](https://etherscan.io/token/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb#readContract) contract I encountered `Eth::Abi::DecodingError`.

I am instanting the contract using `#from_abi` with the ABI taken from the [official source](https://etherscan.io/address/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb#code).

The code _is currently working_ under the combination of [eth.rb](https://github.com/q9f/eth.rb) and [ethereum.rb](https://github.com/EthWorks/ethereum.rb) and my intention is to make use of the newly added smart contract interaction from _eth.rb_ & drop usage of _ethereum.rb_ altogether.

The [official example](https://github.com/q9f/eth.rb#29-interact-with-smart-contract) does seem to work locally, but I don't understand much from this error & the algorithm behind the decoder seems rather complicated (or at least I can't seem to figure out what the issue might be by looking at the code).

```
[28] pry(#<Blockchain::Ethereum::SmartContracts::CryptoPunks::SmartContract>)> @client
=> #<Eth::Client::Http:0x0000ffff70f3b2c0
 @chain_id=5,
 @gas_limit=21000,
 @host="goerli.infura.io",
 @id=8,
 @max_fee_per_gas=0.2e11,
 @max_priority_fee_per_gas=0,
 @port=443,
 @ssl=true,
 @uri=#<URI::HTTPS https://goerli.infura.io/v3/obfuscated_project_id>>
[29] pry(#<Blockchain::Ethereum::SmartContracts::CryptoPunks::SmartContract>)> @contract
=> #<Eth::Contract::CRYPTOPUNKS:0x0000ffff70dd3810>
[30] pry(#<Blockchain::Ethereum::SmartContracts::CryptoPunks::SmartContract>)> @client.call(@contract, 'balanceOf', address)
Eth::Abi::DecodingError: Not enough data for head
from /usr/local/bundle/gems/eth-0.5.4/lib/eth/abi.rb:186:in `decode'
```

### Expected behavior
Successfully call `client.call(contract, 'balanceOf', address)`.

---

I realise there's all the chances I'm doing something wrong, so this might not necessarily be due to a bug.

**Comment by kurotaky** [comment]
@alex-damian-negru 
Hi, I reproduced it with the same ABI. Please wait a moment while I fix it.
