### ISSUE TITLE
comparison of String with Integer failed

### ISSUE THREAD

**Issue by pynixwang** [q9f/eth.rb#110]
I encode a uint256 with a string. eg "10000000000000000000000" from json.

and there is no convert cause this error.

**Comment by pynixwang** [comment]
Abi.encode(["uint256"],["10000000000000000000000"])

**Comment by pynixwang** [comment]
function abi and args are from json body, so I can not convert it explicitly.

**Comment by pynixwang** [comment]
and json can not deal big Number

**Comment by q9f** [comment]
Thank you, I'll try to have a fix soon
