### ISSUE TITLE
eth/contract Testing ETH Contract Deployment using the `eth` Ruby gem against provider endpoints

### ISSUE THREAD

**Issue by unixneo** [q9f/eth.rb#116]
Hope this helps.

I summarized some `eth` issues found when testing with four different blockchain endpoint providers here:

https://community.unix.com/t/testing-eth-contract-deployment-using-the-eth-ruby-gem-against-provider-endpoints/387004

Not sure the best was to continue reporting these issues, as I do not wish to be a pain and inundate anyone with these various issues encountered with testing various endpoints.

Kindly let me know how to proceed without being annoying.   Thanks.

**Comment by unixneo** [comment]
Update:

Tried this, using `sender_key'

```ruby
   key = Eth::Key.new priv: ENV['ETH_CONTRACT_SENDERS_PRIVATE_KEY']
   chain.deploy_and_wait(contract,sender_key:key)
```

Results:

Waiting / stuck here:

```
irb(main):002:0> EthGem::Core.contract("hello_world","alchemy_goerli")
```

not sure how long this should take, being new at this; but it just hangs.

**Comment by unixneo** [comment]
Update:

Twice, it times out, as follows:

```
/Users/tim/rails/eth/vendor/bundle/ruby/3.0.0/gems/eth-0.5.5/lib/eth/client.rb:378:in `block in wait_for_tx': Timeout::Error (Timeout::Error)
```

**Comment by q9f** [comment]
In that case, you need to increase gas fees.

**Comment by unixneo** [comment]
OK. Thanks. Waiting again, after:

```
irb(main):008:0> chain.gas_limit
=> 21000
irb(main):009:0> chain.gas_limit=500000
=> 500000
```

**Comment by q9f** [comment]
not the limit, the fee (price)

**Comment by unixneo** [comment]
Thanks.   

This one, correct?

```
irb(main):005:0> chain.max_fee_per_gas
=> 0.2e11
```

Increase this?

**Comment by unixneo** [comment]
I tried again on "chainstack_ropsten", and it worked, finally (with default settings)

```
irb(main):002:0> EthGem::Core.contract("hello_world","chainstack_ropsten")
Balance is 1.0400990549999952e+20         
FILE: /Users/tim/rails/eth/lib/assets/contracts/hello_world.sol                    
=> "0xb9554BF515750AD073Ec197AD415aEc5b69483D6"
irb(main):003:0> 
```

Yea!   :)

**Comment by unixneo** [comment]
Now, I just need to figure out how to set the gas fee for eth clients, as I could not find it here:

![Screen Shot 2022-06-15 at 8 13 16 PM](https://user-images.githubusercontent.com/12891828/173835509-a5271df1-dcb5-41a1-98a8-44a9c69db1f6.png)

Nor here:


![Screen Shot 2022-06-15 at 8 13 40 PM](https://user-images.githubusercontent.com/12891828/173835575-8d7d3c8d-6d41-4c7d-be62-06f3e9792493.png)

Is it "max_fee_per_gas"  (in GWEI) ?

**Comment by unixneo** [comment]
Also, FWIW, I checked the transaction above (the "successful" one), and it seems it failed for gas reasons as well:

![Screen Shot 2022-06-15 at 9 10 25 PM](https://user-images.githubusercontent.com/12891828/173848718-1b03fbcf-2d5d-4008-a40d-efe13bbdb1ec.png)

Being new to this, I'm confused why gas is such an issue on test networks and why these errors are not being returned to the `eth` client, but they show up on the scanner.

**Comment by q9f** [comment]
> Is it "max_fee_per_gas" (in GWEI) ?

Please read up on EIP 1559. You need to set both, priority and gas fee.

> it seems it failed for gas reasons as well

yes, this is a known issue #111 - I'll make a release shortly.

> It returns the transaction id, but not the status.

Yes, #99

**Comment by unixneo** [comment]
> Please read up on EIP 1559. You need to set both, priority and gas fee.
> 
> >

Yes, I have...  

The problem I am having is that when I read up on these topics on the net, and also in stackexchange and other sites and in other docs, the methods often do not match the methods in the `eth` gem.  

Sorry you are getting frustrated with my questions. but I am only trying to understand how this `eth` gem works and the documentation is not clear and the return values are not providing info.

The best way so far today is for me to just edit the gem and start printing.

For example, you told me that "the gas fees were too low" and that is why I keep getting timeout errors.  However, I checked the client code, and the timeout was sent to 300 seconds.   It is typical for low gas fee transactions to take a lot longer than 5 minutes, but this timeout value of 300 seconds is hardcoded into the client.

Again, sorry you are getting frustrated with my questions.   Honestly, I am simply trying to get this gem to submit a "hello world" contract on Ropsten, Goerli, and Rinkeby test networks and it has been days and I have not got a single simple "hello world" transaction to work.     

I don't think it's my fault :)

**Comment by q9f** [comment]
I'm not frustrated :)

**Comment by unixneo** [comment]
That's nice to hear.  I am worried that my testing and debugging is annoying you :)

So, today I added some debug prints to the gem and have increased gas prices like so:

```ruby
        chain = Eth::Client.create Endpoint::Provider.get(network_provider)
        gas_pump = 1.2
        chain.gas_limit=70000
        gas_price =  chain.max_fee_per_gas
        chain.max_fee_per_gas = gas_price *  gas_pump
        gas_limit=chain.gas_limit
        chain.gas_limit = gas_limit *  gas_pump
        puts "PUMPED UP GAS: chain.max_fee_per_gas=#{chain.max_fee_per_gas} & chain.gas_limit=#{chain.gas_limit}"
```

However, this results in the "replacement underpriced" error:

```
/Users/tim/rails/ethgem/vendor/bundle/ruby/3.0.0/bundler/gems/eth.rb-fe8f91718d62/lib/eth/client.rb:462:in `send_command': replacement transaction underprice
```

So, I increased gas like this:

```ruby
     gas_pump = 1.25
```

and that results in the "already known" error (which I think is nonce related?), as follows:

```
/Users/tim/rails/ethgem/vendor/bundle/ruby/3.0.0/bundler/gems/eth.rb-fe8f91718d62/lib/eth/client.rb:462:in `send_command': already known (IOError)
```

Maybe you can help me out and explain to me how to fix this and move past this (nonce related?) issue so I can actually deploy Hello World ?

Thanks!

**Comment by q9f** [comment]
I'll try to give you a more elaborate answer within the next days, please don't give up yet :)

**Comment by unixneo** [comment]
Here is a quick public version of the code to test this Hello World contract:

https://github.com/unixneo/ethtest.git

Hope this helps.

**Comment by unixneo** [comment]
Update:

Now I get this error:

```
OUTPUT BELOW
{"jsonrpc"=>"2.0",
 "id"=>7,
 "error"=>
  {"code"=>-32000, "message"=>"insufficient funds for gas * price + value"}}
ETH ERROR: contract deployment failed: insufficient funds for gas * price + value
```

And when I look for an answer via google, nothing I change helps to get past this roadblock.    The account I am using has over 300 ETH (not GWEI, ETH) and the signing key for the transactions is the same private key as the address.

Is there a method to simply read what the EVM wants so we can give it want it wants?

**Comment by unixneo** [comment]
Trying yet another way, the error changes again:

```
OUTPUT BELOW
{"jsonrpc"=>"2.0",
 "id"=>6,
 "error"=>{"code"=>-32000, "message"=>"already known"}}
ETH ERROR: infura_ropsten contract deployment failed: already known
```

Seems like the protocol and / or the gem should have methods to deal with this, right?

These seems to be standard errors and the solution would come from information in the EVM, so it seems when these errors occur, either:

1.  The EVM should return "what it wants" or
2. The gem should query the EVM on error and return "what the EVM" wants.

Or, three, what is a method to do this because searching the net has not yielded any fruit.

**Comment by unixneo** [comment]
Chainstack and Infura provided "working" gas params.  Thanks.

**Comment by sai1024** [comment]
> unixneo

hi,  How did you solve it in the end?

**Comment by unixneo** [comment]
TBH: I gave up with `eth.rb`, and impatiently moved on to more pleasant tasks than debugging this repo code (for reasons I will self-redact).

**Comment by q9f** [comment]
Sorry to see you gave up.

Responded to all your questions here: https://community.unix.com/t/creating-a-hello-world-contract-with-ruby-ethereum/388145
