### ISSUE TITLE
Not a bug, but a question seeking to reach the repository owner.

### ISSUE THREAD

**Issue by ytrezq** [q9f/eth.rb#117]
Hello, @q9f, I don’t who to reach nor I found a way to contact you since the discord shutdown, but openethereum didn’t reached the end of it’s course, as there are many analysis tools relying on `parity_liststoragekeys` which is also required for building token richs lists on past blocks and Erigon is unwilling to break database compatibility for bringing the required equivalent fatdb feature which powered this.

I recognize this isn’t the right place to talk about this, so would it be possible to have a chat about this or with the repository owner (taking over)?

**Comment by q9f** [comment]
Sure, just send me a message to parity at q9f dot cc :)
