### ISSUE TITLE
Eth::Contract::FunctionInput drops array brackets from type

### ISSUE THREAD

**Issue by nigimaxx** [q9f/eth.rb#126]
When initializing `Eth::Contract::FunctionInput` with an array type (e.g. `uint256[]`) it returns the a non-array type on it's type method.

This example should make it clear:

```rb
Eth::Contract::FunctionInput.new({ "name" => "array", "type" => "uint256[]" }).type
# "uint256"
```

**Comment by nigimaxx** [comment]
This might solve it! (_At least in my tests it worked_)

```rb
module Eth
  class Contract::FunctionInput
    def type
      @type.base_type + @type.sub_type + @type.dimensions.map{ |dimension| "[#{dimension > 0 ? dimension : ""}]" }.join("")
    end
  end
end

```

**Comment by septerr** [comment]
I am running into a similar issue. I am calling a contract function which returns an `uint256[]` type. But, the gem is parsing the returned value into an `uint256`.

**Comment by septerr** [comment]
> This might solve it! (_At least in my tests it worked_)
> 
> ```ruby
> module Eth
>   class Contract::FunctionInput
>     def type
>       @type.base_type + @type.sub_type + @type.dimensions.map{ |dimension| "[#{dimension > 0 ? dimension : ""}]" }.join("")
>     end
>   end
> end
> ```

This patch works! I used it for `FunctionOutput` alongside the `FunctionInput` :)
