### ISSUE TITLE
Does this gem support Binance Smart Chain transactions (BEP20) ?

### ISSUE THREAD

**Issue by urkishan** [q9f/eth.rb#142]
As I am trying to do a transaction and getting transaction type not found.

So if anyone knows about any reference repository that I can work with to support BSC please let me know.

**Comment by a-moreira** [comment]
BSC is EVM compatible AFAIK so this gem should be enough for you. Can you give more information about what kind of transaction you are trying to send and the error you are getting?

**Comment by urkishan** [comment]
@a-moreira figured that out it was giving the error because of we were adding these two parameters `priority_fee and max_gas_fee` for the BSC and BSC doesn't support this now. With `gas_price` BSC worked fine for me.

**Comment by urkishan** [comment]
We can close this issue.
