### ISSUE TITLE
Status of the repository

### ISSUE THREAD

**Issue by q9f** [q9f/eth.rb#144]
I just wanted to let everyone know that I'm currently heavily involved organizing ETHBerlin³ besides my full-time job at ChainSafe. Unfortunately, I won't be able to address issues and review pull requests before September.

However, this repository has high priority for me and I will make sure we have a patch release ready by end of September!

**Comment by kurotaky** [comment]
I will be presenting at [RubyKaigi 2022](https://rubykaigi.org/2022/schedule/#sep10) on 9/10, so I can't actively respond until then, but I will continue to maintain it!  I will be speaking on eth.rb at this event.

**Comment by q9f** [comment]
Great!
