### ISSUE TITLE
Contract call: when pass type of address[] params, 'Could not parse address' error raised

### ISSUE THREAD

**Issue by kingviewer** [q9f/eth.rb#153]
I was calling the methods of my contract. The is a parameter of type address[] of one method.
When the method called, the error raised: 
eth-0.5.6/lib/eth/abi.rb:424:in `encode_address': Could not parse address: ["0x2574A0c1CD2c55D3FcB3435f5E3174f82375c156"] (Eth::Abi::EncodingError) 

And if a method of contract returns type of address[], the result is not correct.

**Comment by kingviewer** [comment]
The abi of the method:

{
			"constant": false,
			"inputs": [
				{
					"internalType": "address[]",
					"name": "receipts",
					"type": "address[]"
				},
				{
					"internalType": "string[]",
					"name": "uris",
					"type": "string[]"
				}
			],
			"name": "batchMint",
			"outputs": [],
			"payable": false,
			"stateMutability": "nonpayable",
			"type": "function"
		}

**Comment by q9f** [comment]
Yes, I also noticed that. Stay tuned 🙏🏼

**Comment by q9f** [comment]
Let's track this here #143
