### ISSUE TITLE
Connect with meteamask

### ISSUE THREAD

**Issue by dillon-co** [q9f/eth.rb#164]
I saw a you answered [this stack exchange](https://ethereum.stackexchange.com/questions/24364/how-can-i-connect-my-rails-app-to-an-ethereum-network) saying you could authenticate with metamask using this gem. Do you have any examples of how to plug this into the frontend?

Basically I'm trying to login with metamask while avoidin using any NPM packages.. Is that even possible or no?

**Comment by q9f** [comment]
Yes, do you use rails? Have a look at:

* https://docs.login.xyz/libraries/ruby/rails
* https://dev.to/q9/finally-authenticating-rails-users-with-metamask-3fj
* https://github.com/q9f/ethereum-on-rails
* https://github.com/spruceid/siwe-rails-examples/tree/main/rails-engine
