### ISSUE TITLE
Rename `Eth::Client::Http/HttpAuth/Ipc#send` method to `send_request`?

### ISSUE THREAD

**Issue by d4mk0** [q9f/eth.rb#171]
Sometimes I try call `send` method directly i.e. now, I send `eth_client.send(:call_payload, ...)` to get encoded value for next step.
And @q9f what do you think about it?
Can I rewrite `Eth::Client::_child_#send` methods to something like `send_request`?
We also can use `object.__send__` method right now, but it's not obvious

**Comment by q9f** [comment]
I've had issues with the design of how we implement `send` so I would not be opposed to such a change if you want to give this a try.
