### ISSUE TITLE
Not only ethereum net supporting (Gas Limit validation problem)

### ISSUE THREAD

**Issue by d4mk0** [q9f/eth.rb#226]
Hi! 👋 
Sometimes I use this lib to interact with different L2 networks. I.e. optimism, arbitrum

I found few issues, but now I see only one.
I dont know how we can except this problem, but it is problem, and 🐒 (monkeypatching) only now can fix it.

Im about problem with tx gas limit validation.
Now https://github.com/q9f/eth.rb/blob/main/lib/eth/tx.rb#L206 we can only set 30kk limit, but sometimes in L2 we should set it higher.

I think it can be good first issue for some person.
Also we can discuss it in https://t.me/ruby_eth (about EVM like chains)

TY for u attention!

**Comment by MujahidAli954** [comment]
I want to work on this can you assign this to me

**Comment by q9f** [comment]
Sure, let me know if you need anything!

**Comment by samuelarogbonlo** [comment]
Was this issue solved, or is it still actually still open? @q9f @MujahidAli954

**Comment by d4mk0** [comment]
Open
