### ISSUE TITLE
Geth version question

### ISSUE THREAD

**Issue by ndrslmpk** [q9f/eth.rb#234]
As provided in the [docs](https://q9f.github.io/eth.rb/Eth/Api.html), we currently implement the Geth version `1.10.26.`, as I saw the most recent version provided by Geth is `1.11.6` might there any problems occur due to not implementing the most recent version of Geth ?

Should we upgrade as well? And what are the risks of not upgrading the client?

**Comment by q9f** [comment]
It should work with the latest geth perfectly fine. It only affects which APIs we provide natively with the gem.

The worst thing that can happen is that you get an error in case an API has changed. If that is the case, please create a bug report. But for now, don't worry.
