### ISSUE TITLE
missing bech32 depedency

### ISSUE THREAD

**Issue by curtis741** [q9f/eth.rb#239]
Just added this gem to my repo, I also had to add `bech32` as a gem.

**Comment by q9f** [comment]
Hi, could you elaborate on what your gem is and why it requires bech32? The `eth` gem does not implement any functionality that relies on bech32.

**Comment by curtis741** [comment]
oh, I guess I'm pulling in https://github.com/se3000/ruby-eth instead of this newer gem. I'm confused then, both libraries say to install via `gem install eth`...

**Comment by q9f** [comment]
Ah right. You need to install eth 0.5.0 or later.

**Comment by curtis741** [comment]
maybe worth noting that in https://github.com/q9f/eth.rb#installation ? anywise, feel free to close the ticket. I'm all set with this:
```
gem "eth", "~> 0.5.10", github: "q9f/eth.rb"
```
