### ISSUE TITLE
The dependency is broken for 0.4.18 gem version

### ISSUE THREAD

**Issue by spidzio** [q9f/eth.rb#67]
The 0.4.18 version of the gem is dependent on `money-tree ~> 0.11` which does not exist. The latest existing version of the `money-tree` is `0.10`.

**Comment by q9f** [comment]
Closing this as you can either follow the instructions in https://github.com/GemHQ/money-tree/issues/50

Or upgrade to the latest version of `eth` which no longer relies on money tree.

**Comment by spidzio** [comment]
This gem is a dependency for `magic-admin-ruby` which also has a dependency issue and the `eth 0.5` version causes `NameError` for `Eth::Utils` which I can see was renamed to `Eth::Util`. On the other hand, when I freeze `eth < 0.5` it takes 0.4.17 but causes an `openssl` error. I was hoping that 0.4.18 maybe solve the error for now. Meanwhile, I reported the bug in the `magic-admin-ruby` but I'm not sure when will they update their gem to support `eth 0.5`. Thanks for the answer.

**Comment by q9f** [comment]
Ok, I see. Can you test this? https://github.com/magiclabs/magic-admin-ruby/pull/12
