### ISSUE TITLE
eth/client: support resolving ENS domains

### ISSUE THREAD

**Issue by mculp** [q9f/eth.rb#74]
I think this may tie or interfere with the implementation of #72 also.

**Comment by q9f** [comment]
An ::EnsResolver could be part of the client. Once you instantiate a client, it should have the ability to resolve ::Ens to ::Address

**Comment by arenzel** [comment]
That would be great!

**Comment by q9f** [comment]
NameHash: https://docs.ens.domains/contract-api-reference/name-processing

Resolver: https://docs.ens.domains/dapp-developer-guide/resolving-names

**Comment by q9f** [comment]
same address on all networks: `0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e`

https://etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e#readContract

**Comment by mculp** [comment]
I'll work on this next

**Comment by mculp** [comment]
Working on this now.

**Comment by dansimpson** [comment]
@mculp / @q9f I was looking for this as well, and started this here: https://github.com/withfabricxyz/eth.rb/commit/7194b7e4a3af6f4bb2b1578bb410390697aafac3

The biggest issue is in normalizing the domain. The ICU libraries for ruby don't seem to do exactly what is needed. This will work for basic names, but it's not properly encoding tokens with Cyrillic characters, etc. I tried a few libraries, which generate puny code symbols, but that isn't quite enough. See: https://github.com/jcranmer/idna-uts46 , which is used by https://github.com/ensdomains/eth-ens-namehash/blob/master/index.js#L26

**Comment by q9f** [comment]
Thank you, Dan.

I would love to consider accepting this for now. Some thoughts:
- adding a test case to resolve a name on mainnet (we can set an INFURA_ID in CI)
- maybe renaming `Eth::Ens::Resolver::DEFAULT_ADDRESS` to `Eth::Ens::DEFAULT_REGISTRY` or something meaningul in the ::Ens namespace
- We already deploy the registry to our test chain, maybe we can try to set a name and resolve it straight away? https://github.com/q9f/eth.rb/blob/main/spec/eth/client_spec.rb#L107-L113

In general, we can split this up in multiple PRs if you want to only submit the resolver for now and look into the encoding issues later, I'd be happy to review it.

**Comment by mculp** [comment]
@dansimpson The encoding issue was the issue I ran into as well when trying to work on this. I was trying to follow the ENS spec to the T and couldn't seem to find a library that correctly encoded all names.

Thanks for doing this

**Comment by mculp** [comment]
@dansimpson FYI this is the recursive namehash implementation that I had. I ported it from the python reference implementation.

```ruby
      def namehash(name)
        if name.empty?
          "\0" * 32
        else
          label, _, remainder = name.partition('.')
          Eth::Util.keccak256(namehash(remainder) + Eth::Util.keccak256(label))
        end
      end
```

**Comment by mculp** [comment]
@dansimpson If you open a PR, I have a couple pretty minor comments I'd like to make on your changes.

**Comment by musik** [comment]
`
  def namehash(name)
    if name.empty?
      Eth::Util.prefix_hex("00"*32)
    else
      label, _, remainder = name.partition('.')
      Eth::Util.prefix_hex(sha3(namehash(remainder) + sha3(label)))
    end
  end  
  def sha3 str
    str = Eth::Util.hex_to_bin(str) if Eth::Util.is_hex?(str)
    Eth::Util.bin_to_hex(Eth::Util.keccak256(str))
  end  
`

**Comment by mculp** [comment]
@musik yeah, once [this](https://github.com/q9f/eth.rb/pull/76) gets merged these conversions should be easier

**Comment by q9f** [comment]
#150 

#192

**Comment by q9f** [comment]
https://github.com/q9f/eth.rb/wiki/ENS-Resolver
