### ISSUE TITLE
GitPOAP for eth.rb contributors

### ISSUE THREAD

**Issue by kurotaky** [q9f/eth.rb#75]
I want to distribute POAPs with GitPOAP for eth.rb contributors. May need to create a nice badge. 📛 
https://www.gitpoap.io/
If anyone is interested in creating a design for POAP, please feel free to let me know. 😃

**Comment by q9f** [comment]
Yes, I also subscribed to GitPOAP for updates. Currently, it's not possible to issue custom POAPs yet. Let's discuss this on Telegram.

**Comment by kurotaky** [comment]
I see, thanks!
