### ISSUE TITLE
OpenSSL support. Release 0.5 still supports openssl 3.0 but the 0.5.3 branch has be downgraded to OpenSSL 2.2

### ISSUE THREAD

**Issue by Lasvad** [q9f/eth.rb#87]
Hi there,

Is there any plan to bring this back up to openssl 3.0? I need to use the branch 0.5.3 because I need the ability to call a contract which doesn't seem to be supported yet in the main release branch.

```

Bundler could not find compatible versions for gem "openssl":
  In snapshot (Gemfile.lock):
    openssl (= 3.0.0)

  In Gemfile:
    openssl

    eth (= 0.5.3) was resolved to 0.5.3, which depends on
      openssl (~> 2.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

I've tried to downgrade the Openssl gem to version to 2.2 but having issues getting the install to work correctly on my machine.

My main question is, will the OpenSSL 3 dependency be coming back once this hits main branch?

Thanks

**Comment by q9f** [comment]
Just remove your `Gemfile.lock` and run `bundle install`

Blocked by https://github.com/cedarcode/openssl-signature_algorithm/pull/5

Ref #55 #56

**Comment by Lasvad** [comment]
hmm so using just `gem eth`, everything works great for installing the gem
![image](https://user-images.githubusercontent.com/9116207/168503053-4e54360c-d0da-475d-8338-2d3810b63c18.png)
![image](https://user-images.githubusercontent.com/9116207/168503118-293f42b3-b63a-4a18-83ec-c5aaf9899e94.png)

But the issue I'm facing is that I want to interact with contracts. Contracts are documented, but doesn't look like this was implement in `eth.rb 0.5.0` but rather `Eth::Contract` support was added in `eth.rb 0.5.3`.

When I explicitly set the version to 0.5.3, I hit the errors with SSL
![image](https://user-images.githubusercontent.com/9116207/168503212-5c50416b-66f8-47f3-b342-b1ab7e50a303.png) 
![image](https://user-images.githubusercontent.com/9116207/168503248-2105bcc5-0a4f-4e1f-8fba-3d59868ba2c5.png)

deleting my gemfile.lock at this point and re-running `bundle install` leads here 
![image](https://user-images.githubusercontent.com/9116207/168503302-f1e67756-6908-4b2c-9f6b-ef91d5b06d54.png)

I can look into installing openssl 2.2.1 locally, which I think is the issue. I don't have Openssl 2.2.1 installed.

Based on these changes, https://github.com/q9f/eth.rb/pull/56/files, the dependency requires 2.x and would not support 3.x after 3a9514f0256c3aca5c7a14a2099a08c52dbad1e1. I've created a PR which should address this. 

My main intention is to have access to `Eth::Contract` which is only available in eth.rb v5.3 and greater.

**Comment by q9f** [comment]
On a side-note, the `::Contract` is still very early in progress and will change again with 0.5.4.

**Comment by q9f** [comment]
please try the latest release 0.5.4 🚀

**Comment by Lasvad** [comment]
> On a side-note, the `::Contract` is still very early in progress and will change again with 0.5.4.

@q9f Any recommendations for another gem/library to use for Contract support in the mean time? Only need to basic interaction with simply contract like balanceOf/ownerOf (no need to deploy).

**Comment by q9f** [comment]
0.5.4 is released, this is your best shot IMHO.
